In [10]:
'''Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2,
то есть состоящий из 5 строк и 2 столбцов.
Первый столбец должен содержать числа 1, 2, 3, 3, 1,
а второй - числа 6, 8, 11, 10, 7. Будем считать, 
что каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку,
используя метод mean массива Numpy.
Результат запишите в массив mean_a, в нем должно быть 2 элемента.'''
import numpy as np
b = ([1, 6],
     [2, 8],
            [3, 11],
            [3, 10],
            [1, 7])
a = np.array(b)
mean_a = a.mean (axis = 0)
mean_a

array([2. , 8.4])

In [14]:
'''Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние
значения соответствующих признаков, содержащиеся в массиве mean_a. 
Вычисление должно производиться в одно действие.
Получившийся массив должен иметь размер 5x2.'''
a_centered = np.subtract(a,mean_a)
a_centered


array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [26]:
'''Задание 3
Найдите скалярное произведение столбцов массива a_centered.
В результате должна получиться величина a_centered_sp. 
Затем поделите a_centered_sp на N-1, где N - число наблюдений.'''

a1 = a_centered[: , 0]
a2 = a_centered[: , 1]
a_centered_sp=np.dot(a1,a2)
a_centered_sp
N = a.shape[0]
division = a_centered_sp/(N-1)
division

2.0

In [27]:
'''Задание 4**
Число, которое мы получили в конце задания 3 является ковариацией
двух признаков, содержащихся в массиве “а”. В задании 4
мы делили сумму произведений центрированных признаков на N-1,
а не на N, поэтому полученная нами величина является несмещенной
оценкой ковариации.'''
np.cov(a.transpose())


array([[1. , 2. ],
       [2. , 4.3]])

In [29]:
'''Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. 
Создайте датафрейм authors со столбцами author_id и author_name,
в которых соответственно содержатся данные: [1, 2, 3] 
и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, 
book_title и price, в которых соответственно содержатся данные: 
[1, 1, 1, 2, 2, 3, 3], 
['Отцы и дети', 'Рудин', 'Дворянское гнездо',
'Толстый и тонкий', 'Дама с собачкой',
'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].'''
import pandas as pd
import numpy as nm
authors = pd.DataFrame({'author_id':[1, 2, 3],
                       'author_name':['Тургенев', 'Чехов', 'Островский']})

book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                       'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 
                                     'Толстый и тонкий', 'Дама с собачкой', 
                                     'Гроза', 'Таланты и поклонники'],
                    'price':[450, 300, 350, 500, 450, 370, 290]})


author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [30]:
'''Задание 2
Получите датафрейм authors_price, соединив датафреймы authors
и books по полю author_id.'''
authors_price = pd.merge(authors, book,
   on = 'author_id' , how = 'inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [32]:
'''Задание 3
Создайте датафрейм top5, в котором содержатся строки из authors_price 
с пятью самыми дорогими книгами.'''
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [34]:
'''Задание 4
Создайте датафрейм authors_stat на основе информации из authors_price.
В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора
,минимальная, максимальная и средняя цена на книги этого автора.'''
df1 = authors_price.groupby('author_name').agg({'price': 'min'}).rename(columns={'price':'min_price'})
df2 = authors_price.groupby('author_name').agg({'price': 'max'}).rename(columns={'price':'max_price'})
df3 = authors_price.groupby('author_name').agg({'price': 'mean'}).rename(columns={'price':'mean_price'})
authors_stat=pd.concat([df1, df2, df3], axis = 1)
authors_stat


min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

In [36]:
'''Создайте новый столбец в датафрейме authors_price под названием cover,
в нем будут располагаться данные о том, какая обложка у данной книги
- твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].'''
df1 = pd.DataFrame({'cover':['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']}, columns=['cover'])
authors_price = pd.concat([authors_price, df1], axis = 1)
authors_price

In [ ]:
'''Просмотрите документацию по функции pd.pivot_table
с помощью вопросительного знака.'''
?pd.pivot_table

In [37]:
'''Для каждого автора посчитайте суммарную стоимость книг
в твердой и мягкой обложке. Используйте для этого функцию
pd.pivot_table. При этом столбцы должны называться
"твердая" и "мягкая", а индексами должны быть фамилии авторов.
Пропущенные значения стоимостей заполните нулями,
при необходимости загрузите библиотеку Numpy.'''
book_info = pd.pivot_table(authors_price, values='price',
                           index=['author_name'],
columns=['cover'], aggfunc=np.sum, fill_value=0)

ValueError: Grouper for 'cover' not 1-dimensional